### ISSUE TITLE
Allowing listed `"n/a"` in `Contamination*` fields

### ISSUE THREAD

**Issue by TCLamnidis** [poseidon-framework/poseidon2#28] opened 2022-02-22 15:16 UTC
Contamination estimates are library specific, and when multiple libraries are provided, according to the scheme, their estimates should be reported separated by `;`. 

However, at times, the contamination estimation for a library might fail or not be available. When libraries are merged, it is important to not which library a specific contamination estimate/error is from, regardless of the performance of other libraries. 

Currently, Something like the field below is not a valid janno entry (according to `as.janno()`).

| Poseidon_ID | Nr_Libraries | Capture_Type | UDG | Library_Built |  Contamination | Contamination_Error |
|-------------|-----------|-------|--------|-------|--------|--------|
| IND001  | 2 | Shotgun;Shotgun | minus | ss | n/a;-0.023 | n/a;n/a |

However, I would argue, it should be possible to specify that the contamination error comes from the second library (especially in cases where that library is not of the same `Capture_Type`.

This behaviour possibly needs fixes in `poseidon-hs` as well?

**Comment by TCLamnidis** [comment] 2022-02-22 15:35
```
> readr::write_tsv(output_janno, "~/test.janno")
                                                                                                                             
> output_janno %>% poseidonR::as.janno()
Error in strsplit(res, ";") : non-character argument
> poseidonR::read_janno("~/test.janno")
Validating .janno files...
No issues with these .janno files     
```

**Comment by TCLamnidis** [comment] 2022-02-22 15:36
I actually found that converting all entires to strings and filling `NA`s with `"n/a"` seems to do the trick, so perhaps the error is not based on the validation function?

```
output_janno %>% dplyr::mutate(dplyr::across(.fn=as.character)) %>% replace(is.na(.), "n/a") %>% poseidonR::as.janno()
```

**Comment by TCLamnidis** [comment] 2022-02-22 15:44
As a double-check, I used `write_janno` to save `output_janno`, and replaced the original `janno` file of the package it came from. This is the error I get from `trident validate`. 
```
$ trident validate -d trident_list_test/
trident v0.21.0 for poseidon v2.4.0
https://poseidon-framework.github.io

Searching POSEIDON.yml files... 1 found
Checking Poseidon versions... 
Initializing packages... 
> 1 Can't read sample in trident_list_test/trident_list_test.janno in line 2: parse error (Failed reading: conversion error: empty) at ""
Can't read sample in trident_list_test/trident_list_test.janno in line 3: parse error (Failed reading: conversion error: empty) at ""
Can't read sample in trident_list_test/trident_list_test.janno in line 4: parse error (Failed reading: conversion error: empty) at ""
Can't read sample in trident_list_test/trident_list_test.janno in line 5: parse error (Failed reading: conversion error: empty) at ""
Can't read sample in trident_list_test/trident_list_test.janno in line 6: parse error (Failed reading: conversion error: empty) at ""

Some packages were skipped due to issues:
In the package described in trident_list_test/POSEIDON.yml:
Consistency issues in .janno file trident_list_test/trident_list_test.janno: Broken lines
Packages loaded: 0
Validation failed ✗
```

**Comment by stschiff** [comment] 2022-02-24 10:07
Hmm... does that have something to do how we encode missing values in Poseidon? Is that well-specified? I'm trying to understand whether that's an issue with the spec, or with the various implementations on it...

**Comment by nevrome** [comment] 2022-02-24 10:12
I think it's an issue of the implementation. The standard is not very precise on this front. I just assumed that all contamination estimates would always come with a mean and an error and wrote the code accordingly.

**Comment by nevrome** [comment] 2022-02-24 10:52
Upon closer inspection there are two mixed issues. Thiseas assumed that the standard covers contamination estimates per library. That is not the case. At least not so far. "Multiple contamination estimates" as described in the standard mean multiple methods to measure contamination. This does not refer to different libraries. If we want that feature, then we have to amend the standard.

Right now the standard says this:
> Contamination_Err, Contamination_Meas and Contamination_Note must have the same number and order of entries, in case of multiple libraries report a value from the merged read alignment

The important observations:
- The contamination estimate is not a per-library value
- Empty contamination error values are not allowed
- [x] The standard is wrong in at least one way, because it should say this:
> Contamination, Contamination_Err and Contamination_Meas must have the same number...

**Comment by nevrome** [comment] 2022-02-24 10:55
We can now discuss if we 
1. want to implement per-library contamination estimates
2. want to allow empty contamination error values

Right now, the implementation reflects the standard and there is no imperative to fix the code. What I initially wrote - also in our conversation, @TCLamnidis - was wrong.

**Comment by nevrome** [comment] 2022-02-24 11:04
I also remembered now, that poseidonR [does not even check these semantics yet](https://github.com/poseidon-framework/poseidonR/issues/26). Only trident does that. So there is a third issue in the way you used the poseidonR package, Thiseas. Maybe a phone call is advisable now.

**Comment by stschiff** [comment] 2022-02-24 11:21
Yes, I agree, perhaps we should have a call about this. I remember discussing with @wolfgangaroo at the time, and we decided that we do not need per-library values here, we explicitly decided to have only one value that can be used for filtering or so. For example, in @TCLamnidis case, we could simply ask him to report only the maximum contamination across all libraries for that specific method. 

Alternatively, we could discuss changing the standard and allowing per-library estimates... I don't know... in many cases I think we frankly don't even have per-library values ready, we only have a single estimate, and who knows how that master value was generated in case of multiple libraries. David's AADR is clear on this, he does report per library...

*sigh*.

**Comment by nevrome** [comment] 2022-02-24 16:13
Thiseas and I had a brief call to go through the issues. Here's what emerged from the discussion:

- Given the high level of abstraction of Poseidon, which only considers a very derived data product (genotypes), it could actually be a sensible decision to not give per-library contamination estimates. The assumption would be, that whoever prepares the genotype data in Poseidon format already makes some decisions, which libraries to use and which to discard. So it might be fair to only report a summary statistic for the libraries actually used.
- Allowing empty values for `Contamination_Err` might not be very meaningful, because 1. all methods and tools we know yield an error estimate and 2. if e.g. ANGSD does not report an error value, then the value in `Contamination` is also not reliable (and it is thus not useful to report it). So the current setup of enforcing the presence of all three  `Contamination`,  `Contamination_Err` and `Contamination_Meas` if one of them is filled, is justified.
-  The specific issues Thiseas experienced, were most likely caused by a mixture of using outdated versions and the crude interface of poseidonR.

ToDos I see based on that:
- [ ] The documentation of the `Contamination_*` columns on the website has to be adjusted to be correct and more specific.
- [ ] We have to explain better, where the standard can be found and distinguish clearly between standard and documentation. Probably a change in how we store and maintain information in the standard repo is required.
- [ ] The poseidonR interface should get some more polish. It only covers a number of rather specific use cases right now.

**Comment by TCLamnidis** [comment] 2022-02-25 15:56
My two cents on the above ToDos:
I found poseidonR to work well enough, and I am not sure how much use it is seeing currently apart from reading in a janno file. A way to 'standardise' janno files (say from any version to the latest/a specific version) would help perhaps, when reading files from different version, but even that might be too large a headache given the current user base. 

Regarding linking documentation to the standard, it might be worth looking into the nf-core system. Namely, all the information you currently have [here](https://github.com/poseidon-framework/poseidon2-schema/blob/master/janno_columns.tsv) would be kept in a json file, which is then read into the docs webpage and rendered on the fly. That would save a lot of editing of specific bits as the schema gets updated with additional fields and definitions.
example: eager's parameters within the [nf-core/eager schema](https://github.com/nf-core/eager/blob/master/nextflow_schema.json) vs on the [nf-co.re/eager website] (https://nf-co.re/eager/2.4.2/parameters). The latter is rendered from the former directly.
Granted, this would probably require some overhead.

**Comment by nevrome** [comment] 2022-02-25 16:01
The idea to transform the two tables to a json/yml file is pretty good.

**Comment by stschiff** [comment] 2022-02-28 11:23
Yes, I think we should ideally synchronise changes we make to the schema and the documentation. I don't think JSON/YAML will change anything though... We already have the schema in a machine-readable format. We could simply write a little Javascript component in Vue that loads the TSV we currently have for the Janno schema, and layouts that on the documentation page. In my view, whether this would be JSON/YAML or TSV doesn't make much difference... as long as it's machine-readable.

**Comment by nevrome** [comment] 2022-02-28 12:10
My hope with a switch to .yml was to increase the readability on GitHub. But a dedicated page on the website would solve that as well. Probably that's even better: To have everything at one place, finally.

**Comment by nevrome** [comment] 2023-01-11 14:44
This discussion went beyond the original issue. I close this here. Better integration of schema repo and website will be discussed elsewhere.

**Closed as completed by nevrome** 2023-01-11 14:44 UTC
